framework:
    messenger:
        default_bus: command.bus
        buses:
            # TODO : Uncomment when installing doctrine
            command.bus: ~
                # middleware:
                    # - doctrine_transaction
            query.bus: ~

        transports:
            sync: 'sync://'

        routing:
