parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Shared\:
        resource: '../src/Shared'
        exclude:
            - '../src/Shared/Infrastructure/Symfony/Kernel.php'
